### ISSUE TITLE
asciiVideo and videoGrabberExample examples problems on Win32

### ISSUE THREAD

**Issue by steven-chith** [microsoftarchive/openFrameworks#11]
During comparison test of Win32 and ARM following errors noticed:

asciiVideo:
exception on Win32 version: Unhandled exception at 0x753DA5BD (combase.dll) in asciiVideo_winrt.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x0DA7E54C, 0x00000001).

videoGrabberExample:
exception on Win32 version: Unhandled exception at 0x756CA5BD (combase.dll) in videoGrabberExample_winrt.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x0859E14C, 0x00000001).

**Comment by steven-chith** [comment]
These are caused by the video recording functionality. Once it's perfected these should be tested again.

**Comment by stammen** [comment]
videoGrabber Example works as is. Dave will test asciiVideo.

**Comment by stammen** [comment]
asciiVideo Examples works as is in winrt-multitouch branch. Use release build for best performance.
