### ISSUE TITLE
vboExample has problems comparing to Win32 app

### ISSUE THREAD

**Issue by steven-chith** [microsoftarchive/openFrameworks#12]
Artifacts on the ARM device.

**Comment by steven-chith** [comment]
I get artifacting on both win32 and ARM, unless I hold a button and it switches to ofVboMesh mode. Do you get the same?

**Comment by steven-chith** [comment]
Yes, we have the same.

**Comment by steven-chith** [comment]
Interesting. I tested the original desktop build to see if it also happens there, but it doesn't. After further testing I noticed the artifacting happens every 9th draw call. Nothing in the application's logic changes, so I'm guessing it may be a bug in angle. I'll have to look into it while stepping through angle.

**Comment by ghost** [comment]
P2. Steven- please investigate

**Comment by steven-chith** [comment]
Fixed after switching to newer version of ANGLE.
