### ISSUE TITLE
Errors in audioInputExample and audioOutputExample

### ISSUE THREAD

**Issue by steven-chith** [microsoftarchive/openFrameworks#13]
Following errors at linking for audioInputExample and audioOutputExample:

1>openFrameworksLib_winrt_debug.lib(ofRtAudioSoundStream.obj) : error LNK2001: unresolved external symbol "public: __thiscall RtAudio::RtAudio(enum RtAudio::Api)" (??0RtAudio@@QAE@W4Api@0@@Z)
1>openFrameworksLib_winrt_debug.lib(ofRtAudioSoundStream.obj) : error LNK2001: unresolved external symbol "public: __thiscall RtAudio::~RtAudio(void)" (??1RtAudio@@QAE@XZ)
1>openFrameworksLib_winrt_debug.lib(ofRtAudioSoundStream.obj) : error LNK2001: unresolved external symbol "public: void __thiscall RtAudio::openStream(struct RtAudio::StreamParameters *,struct RtAudio::StreamParameters

**Comment by steven-chith** [comment]
No more linker errors. audioInput works, but audioOutput doesn't output sound yet. Need to go back to rtAudio and implement sound playback.

**Comment by steven-chith** [comment]
audioOutput works now. It doesn't sound exactly like the original desktop version yet. Just gotta figure out where to convert the signal if that's necessary.

**Comment by ghost** [comment]
please make sure that the sound difference isn't due to a mono vs. stereo discrepancy. settings should be consistent.

**Comment by steven-chith** [comment]
Works now. Had to fix a lot of heap corruption issues.
