### ISSUE TITLE
Build errors in imageSequenceExample and lutFilterExample

### ISSUE THREAD

**Issue by steven-chith** [microsoftarchive/openFrameworks#14]
For imageSequenceExample:
First-chance exception at 0x76112EEC in imageSequenceExample_winrt.exe: Microsoft C++ exception: Poco::PathNotFoundException at memory location 0x0344D9EC.
Unhandled exception at 0x52B83C68 (msvcr120d_app.dll) in imageSequenceExample_winrt.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.

For lutFilterExample similar error:
First-chance exception at 0x76112EEC in lutFilterExample_winrt.exe: Microsoft C++ exception: Poco::PathNotFoundException at memory location 0x00FCDC4C.
Unhandled exception at 0x52AA3C68 (msvcr120d_app.dll) in lutFilterExample_winrt.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.

**Comment by steven-chith** [comment]
Those issues don't seem to be occurring anymore.

**Comment by steven-chith** [comment]
Artem can you please verify and close if warranted?

**Comment by steven-chith** [comment]
Different addresses which is absolutely possible, however I there're still issues present.

imageSequenceExample:
a. Win32:
Unhandled exception at 0x61733C68 (msvcr120d_app.dll) in imageSequenceExample_winrt.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.
b. ARM:
Unhandled exception at 0x66489073 (msvcr120_app.dll) in imageSequenceExample_winrt.exe: 0xC0000005: Access violation reading location 0x000F31F8.

lutFilterExample:
a. Win32
Unhandled exception at 0x61733C68 (msvcr120d_app.dll) in lutFilterExample_winrt.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.
b. ARM:
Unhandled exception at 0x5B99D4E5 (msvcr120d_app.dll) in lutFilterExample_winrt.exe: 0xC0000005: Access violation reading location 0x004246FC.

**Comment by ghost** [comment]
P1- please take a look

**Comment by steven-chith** [comment]
I couldn't get imageSequenceExample to throw any exceptions. However, lutFilterExample does, but it has to do with the video capture code. Will revisit again once the video capture code is done.

**Comment by stammen** [comment]
lutFilterExample now works in winrt-multitouch branch. Use release build for best performance.
imageSequenceExample works fine,
