### ISSUE TITLE
multiTextureShaderExample has linker errors

### ISSUE THREAD

**Issue by steven-chith** [microsoftarchive/openFrameworks#15]
missing headers; then linker errors for multiTextureShaderExample

**Comment by steven-chith** [comment]
We need to implement video playback to get rid of those linker errors.

**Comment by stammen** [comment]
App now fails when trying to compile shader. compiler is failing on an assert:

Program: Application
File: ....\src\compiler\translator\SymbolTable.cpp
Line: 67

Expression: false

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

**Comment by steven-chith** [comment]
The shader has some code not supported by OpenGL ES, so that's why it breaks the translator, although why it breaks has something to do with an unhandled case during the translation process which I think falls onto Google's shoulders to figure out. I changed the sampler2DRect to sampler2D and texture2DRect to texture2D and that fixed it, but since it's an example I'll leave it as is, but that's the solution to this bug.
