### ISSUE TITLE
3DPrimitivesExample fail on micro/camera selection

### ISSUE THREAD

**Issue by steven-chith** [microsoftarchive/openFrameworks#16]
WinStore version suggests to use micro and camera and fails on any choice in 3DPrimitivesExample

**Comment by steven-chith** [comment]
Will you take a look at Package.appxmanifest, look under the Capabilities tab, and see if Microphone and Webcam are checked?

**Comment by steven-chith** [comment]
Yes, Microphone and Webcam are checked in Package.appxmanifest.

**Comment by steven-chith** [comment]
What kind of failure is it? Does it say first chance exception?

**Comment by steven-chith** [comment]
In case of blocking:

First-chance exception at 0x75672EEC in 3DPrimitivesExample_winrt.exe: Microsoft C++ exception: Platform::AccessDeniedException ^ at memory location 0x0122D43C. HRESULT:0x80070005 Access is denied.

WinRT information: Access is denied.

Stack trace:
[External Code]

If there is a handler for this exception, the program may be safely continued.

File ofWinrtVideoGrabber.cpp, line 73 (auto mediaCapture = m_mediaCaptureMgr.Get();)

In case of allowing:

Unhandled exception at 0x755DA5BD (combase.dll) in 3DPrimitivesExample_winrt.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x0E1CE564, 0x00000001).

C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\crt\src\vccorlib\init.cpp
Line 135 (::SetRestrictedErrorInfo(exInfo->restrictedInfo.Get());)

Previous part of call stack is missing because of [External Code]

**Comment by ghost** [comment]
P2- please repro

**Comment by steven-chith** [comment]
This happens due to the video capture code. Will revisit when it's finished.

**Comment by stammen** [comment]
video now works fine in winrt-multitouch branch. 

Note: press v key several times to enable camera texture.
