### ISSUE TITLE
[winrt branch] IDE files in examples (also, Assets folders)

### ISSUE THREAD

**Issue by bilderbuchi** [microsoftarchive/openFrameworks#18]
Hey!

As per the mailing list thread, I'll post here what occured to me from glancing over the winRT branch. 

You have changed the `examples/.gitignore` and added IDE files to all the examples. We don't do that, and instead create any IDE/OS-related files for the examples on demand, according to platform, using the (advanced/old) project generator in `apps/devApps/projectGenerator`, before generating a release download. 
People working with the git repo directly (i.e. advanced users) do this themselves.

Regarding Assets folders, I think a better approach would be to create those, too, when creating winRT examples with the advanced PG (and gitignore them in the OF repo).
The files they contain seem to be all identical, _and_ they are only relevant for the winRT platform, so that's even more indication that they should not be in the examples' directories themselves. 
Should this not be possible, we should look at putting the winRT examples into their own subdirectory within /examples, just like with android and ios. @arturoc will probably know more about how to best approach this.

btw, I don't know what files `*TemporaryKey.pfx` are, but from the file name they sound like they should not be in version control?

**Comment by bilderbuchi** [comment]
Also, it's not necessary to add `.gitkeep` files to folder which contain other files in version control. If you have any questions about git usage, feel free to ping me. :-)

**Comment by steven-chith** [comment]
We'll remove the IDE exceptions. It was left over when we were doing initial tests and we needed the projects prepped properly prior to our implementation of the project generator.

The assets folder is really just used as a template for users who wish to add their own custom launcher icon, but these images are required to deploy, so that's why they're there.

As for the TemporaryKey.pfx I don't have a clue what they're for, but without them the apps will still deploy and run, but they'll go all wonky.

**Comment by bilderbuchi** [comment]
> The assets folder is really just used as a template for users who wish to add their own custom launcher icon, but these images are required to deploy, so that's why they're there.

I didn't mean that the Assets images are not necessary, just that they should be copied into the examples when they're generated (along with the IDE files, I'd say).

**Comment by steven-chith** [comment]
I just figured out you meant that a minute ago while I was cleaning out the project files. It's all good now.

**Comment by bilderbuchi** [comment]
Erm, why close this issue? did you already implement the fix (to the PG too)? I don't see any new commits, so I presume it's in the private branch?
Regarding the TemporaryKey.pfx files, apparently they are related to signing apps, and fine to be in version control: http://stackoverflow.com/a/12331157/599884

**Comment by steven-chith** [comment]
Oh, it's actually in the xaml branch of this repo. @stammen is working on the winrt branch to make sure all the work we did shows up in the commits and will merge the xaml branch in when he's done. Should we keep this open until he gets that done?

**Comment by bilderbuchi** [comment]
ah thanks. it's still necessary to undo the changes to `examples/.gitignore` [here](https://github.com/MSOpenTech/openFrameworks/blob/6bec1ba2a3aa0e13ceb009e0f0495101719e0029/examples/.gitignore#L25-L30), and to add a new rule so that Assets folders stay ignored. I think `*/*/Assets/` added [here](https://github.com/MSOpenTech/openFrameworks/blob/6bec1ba2a3aa0e13ceb009e0f0495101719e0029/examples/.gitignore#L7) should do the trick, but kindly confirm this yourself, too.

**Comment by bilderbuchi** [comment]
As for closing, I think better leave it open for now, as there's going to be some more work necessary (I think) in the advanced PG to also create the Assets folders along with copying the IDE files. I'll leave that up to your issue tracking style, though.

**Comment by steven-chith** [comment]
Thanks for reminding me about the .gitignore. I fixed the ignores. I think I'll just keep this open for now.
