### ISSUE TITLE
[winrt branch] minor issues

### ISSUE THREAD

**Issue by bilderbuchi** [microsoftarchive/openFrameworks#19]
#### docx license files

text files like `NOTICE.TXT - ANGLE.docx` - why are those docx, instead of plain `txt` files? I think it would be better (and consistent with the rest of OF), if those were plain text files. (I think this applies to `rtf` files, too)
#### library builds

We're currently trying to transition to (semi)automated library builds, so if your library cannot be included as source (how big is angle?), take a look at https://github.com/danomatika/apothecary which is a solution to build and refresh compiled libs - there are recipes according to libs and platforms, @danomatika and @bakercp can tell more. This is more for the long run, but it's something we can keep in mind.
#### branch is rough WIP, right?

I'm just wondering, cause I see blocks of commented out code, e.g. in libs/openFrameworks/communication/ofSerial.cpp `void ofSerial::enumerateWin32Ports()` and others. I guess we will cherry-pick commits over into an integration branch or somesuch?

**Comment by steven-chith** [comment]
We'll change out the license formats to .txt.

Angle isn't very big, definitely smaller than openFrameworks. It would be nice to be able to build the libs from source, especially as Microsoft continually updates Visual Studio and requiring rebuilds of all those underlying libs. We had to do that for the winrt build of oF for every library in use.

Most of the code that's commented out is code that's not supported in winrt, like the one you mentioned, but there are a few exceptions that are still doable and they're just commented out so we have a template to work off of when we get around to implementing them.

**Comment by bilderbuchi** [comment]
> Most of the code that's commented out is code that's not supported in winrt

I see, thanks for the clarification. Keep in mind that winrt is not the only player in town, OF supports 6 platforms or so, so when collecting the changes to merge from this, care has to be taken that no changes slip into OF that break it for other platforms.

**Comment by steven-chith** [comment]
The licenses are now converted to plain text.

**Comment by bilderbuchi** [comment]
thanks :-)

**Comment by bilderbuchi** [comment]
thanks! hm, would you mind renaming those to `LICENSE.txt` or similar? `NOTICE.TXT - library.txt` is a pretty unusual and non-intuitive filename. :P

**Comment by steven-chith** [comment]
Renamed the licenses.
