### ISSUE TITLE
[WinRT branch] Single Solution

### ISSUE THREAD

**Issue by LeoColomb** [microsoftarchive/openFrameworks#21]
Hi,
Thanks for this beautiful work, really amazing!

One note, following #18, it's about solutions.
In the past, I've manage to get openFrameworks VS2012 ready, and worked to regroup all Win+VS in a comprehensive single solution.

I see here you have created separate `_winrt.sln` solutions and respective `_winrt` projects. Issues:
- We can't compare easily how do you manage dependencies nor follow what is changed in respective configurations;
- We won't be able to merge these `winrt` solutions with current Win32 solutions.

Since VS2012/2013 supports multiple targets (and even has a an impressive target manager) with receptive configuration, it should be **super** useful to regroup everything in a general solution.

Also, I'm currently (more or less because free time is rare) working on VS2013 support + x64 support. See https://github.com/openframeworks/openFrameworks/pull/2571 (feel free to pull changes), and seriously, again, regroup Win32, x64, ARM for Windows & Windows RT in a single solution will increase productivity for us and for "users".

**Comment by ghost** [comment]
Need to revisit as part of pull request discussion.

**Comment by stammen** [comment]
May become possible with VS 2015. Will revisit later.
