### ISSUE TITLE
[WinRT branch] projectGeneratorSimple_winrt.exe crash : let it crash gracefully

### ISSUE THREAD

**Issue by ericmitt** [microsoftarchive/openFrameworks#22]
Hi, if you run projectGeneratorSimple_winrt.exe and click on Addons button, it crashes.
I think it’s because the components are not ready for WinRT, but can we crash gracefully?

For example we can disable the AddsOn button, or having a dialog box explained that at this time the addons are not ready…

Eric

**Comment by steven-chith** [comment]
It crashes due to passing invalid data to the renderer, but for now I disabled the button.

**Comment by ericmitt** [comment]
great I''l test it 
Thanks
