### ISSUE TITLE
OF renderer fails on high PPI displays

### ISSUE THREAD

**Issue by ghost** [microsoftarchive/openFrameworks#23]
We need to test on multiple pixel density displays, as this bug only occurs on high PPI displays; it does not show up with "typical issue" hardware.

On a high PPI display, such as a Macbook Pro with Retina, bootcamping directly into Windows 8.1 ( NOTE: For OF users, this will be a VERY common hardware configuration ) - the rendering is way off.

On the winrt-multitouch branch: 

Go to Project Generator and create a simple project. In ofApp.cpp, do the most basic rendering test:

void ofApp::draw() {   ofCircle(100, 100, 100);  }

if you run it on a high PPI display, the circle starts half way down the screen ( instead of at the upper left corner ).  If you start reducing the Screen Resolution ( the recommended default settings on the Retina Display is 2560 x 1600 ), the circle will gradually get larger and move up the screen.

I needed to drop my screen resolution from 2560 x 1600 to 1440 x 900 before the ofCircle(100,100,100); actually drew the circle in the proper location.

This one is pretty big, we need to take the PPI into account when we're handling the rendering logic.

**Comment by ghost** [comment]
I'm basically locked out of working with OpenFrameworks and further testing until this is resolved.

**Comment by steven-chith** [comment]
I got proper scaling in. Give it a try and see if you run into any problems.

**Comment by ghost** [comment]
The scaling isn't consistent / isn't keeping the correct aspect ratio.

Test: Run OF WinRT-multitouch branch on high PPI display.

In my case, its a Bootcamped MacBook Pro into Windows 8.1, with the default 2560x-1600 recommended resolution.

I create a new project, in the draw() function I simply write:

draw() {  ofCircle(100, 100, 100); }

and it draws an upright ellipse instead of a circle. ( the width is scaled less than the height ). 

2nd test:

you try and draw a circle in the middle of the screen like this:

```
ofCircle( ofGetWidth()/2, ofGetHeight()/2, 800);
```

and the circle is drawn off center ( closer to the left, as you would expect if the width was scaling smaller than the height ). It also is drawn as a tall ellipse instead of a circle.

It seems like the aspect ratio is also affecting the scale or stretch. We prob. want to make sure it isn't anything wonky happening since we're inside (under? rendering into) a XAML component as well and we're getting some funky app level scale / stretch by default since we instantiate OF in main.cpp with the default 1280x800, no?

**Comment by steven-chith** [comment]
Fixed it. It was due to a bug, or rather a design oversight, in ANGLE that limited the viewport size to 2048x2048 pixels. Not sure why this only happens on XAML projects, but everything looks good now.
