### ISSUE TITLE
[WinRT-Multitouch branch] Missing lib in projects settings when using project generator (win32 project)

### ISSUE THREAD

**Issue by olivierbloch** [microsoftarchive/openFrameworks#24]
Repro steps:
git clone https://github.com/MSOpenTech/openFrameworks.git -b winrt-multitouch

launched ProjectGeneratorSimple.exe
created new app
added the following code in the Draw function (cam is an ofEasyCam object added to the .h file)
    ofBackground (0);
    ofColor(255);
    cam.begin();
    ofSphere(100,100,100);
    cam.end();

Compiled
got Link error:
Error   13  error LNK2019: unresolved external symbol __imp__timeGetTime@0 referenced in function "unsigned __int64 __cdecl ofGetSystemTime(void)" (?ofGetSystemTime@@YA_KXZ)   C:\Users\obloch\Documents\GitHub\openFrameworks\apps\myApps\mySketch\openframeworksLib_debug.lib(ofUtils.obj)   mySketch

Adding winmm.lib to the input libs fixes the issue... BUT using the main branch I don't have to add winmm.lib...

**Comment by steven-chith** [comment]
Fixed by adding pragma to link lib in ofAppGLFWWindow.cpp. Should work through ofAppGlutWindow.cpp, but it doesn't, but I'll look into why that is later.
