### ISSUE TITLE
[WinRT-Multitouch branch]  ofSphere throws exception

### ISSUE THREAD

**Issue by olivierbloch** [microsoftarchive/openFrameworks#25]
Repro steps
Created new project with ProjectGeneratorSimple.exe
added following code in the Draw function:

ofBackground (0);
 ofColor(255);
 cam.begin();
 ofSphere(100,100,100);
 cam.end();

Where cam is an ofEasyCam object added in the .h file of the project.
ofSPhere throws exception:
Unhandled exception at 0x0F2E9300 (ig75icd32.dll) in mySketch_debug.exe: 0xC0000005: Access violation reading location 0x00000010.

**Comment by steven-chith** [comment]
I fixed it. I commented some important OpenGL code when I was working oF for winrt so I uncommented them and prevented them from interfering with the winrt code.
