### ISSUE TITLE
mesh.setMode(OF_PRIMITIVE_POINT) Doesn't work.

### ISSUE THREAD

**Issue by ghost** [microsoftarchive/openFrameworks#26]
Test:

In header, create mesh object:

ofMesh mesh;

Add this to your Class:

void testApp::setup() {
    mesh.setMode(OF_PRIMITIVE_POINTS);

```
ofVec3f top(100.0, 50.0, 0.0);    
ofVec3f left(50.0, 150.0, 0.0);    
ofVec3f right(150.0, 150.0, 0.0);

mesh.addVertex(top);
mesh.addVertex(left);
mesh.addVertex(right);
```

}
void testApp::draw() {
    ofBackground(0);
    mesh.draw();
}

You should see three white points. You don't see anything.

By changing the Mesh modes to anything other than POINT, it works ( OF_PRIMITIVE_LINE, etc.)

**Comment by stammen** [comment]
Try setting glPointSize(    GLfloat size);

However, PointSprites may not work on WinRT Angle version.

**Comment by steven-chith** [comment]
ANGLE prevented points from being drawn if point sprites were unavailable, so I told it not to do that.
