### ISSUE TITLE
ofShader compilation errors are not output to the debug window

### ISSUE THREAD

**Issue by stammen** [microsoftarchive/openFrameworks#27]
Shader compilation errors are not output to the debug window.
1. Try to load a bad shader into ofShader
2. Expect shader compile errors to be displayed
3. No error message with the compiler error is displayed.

**Comment by steven-chith** [comment]
Made logger output to output window in Visual Studio for winrt.

**Comment by stammen** [comment]
It looks like shader compile errors are not being logged with winrt-es3proto version of angle.
