### ISSUE TITLE
WinRT project generator crashes when checking addons

### ISSUE THREAD

**Issue by ghost** [microsoftarchive/openFrameworks#28]
Launch the project generator for WinRT and it will always crash when trying to access addons.

**Comment by steven-chith** [comment]
You must be using the older version on the winrt branch. The latest one on the winrt-multitouch branch works fine which is where we're going to be focusing all our development., The addons button is disabled. I fixed the crash, just need to add the new generator.

**Comment by steven-chith** [comment]
Got the latest project generator pushed on the winrt-multitouch branch.
