### ISSUE TITLE
Empty app crashes on Exit (ESC)

### ISSUE THREAD

**Issue by ghost** [microsoftarchive/openFrameworks#29]
Just moved over to Windows so this could be an obvious fix to some... Just running an empty app and when I press ESC to quit it crashes.

First-chance exception at 0x754C2EEC in mySketch_winrt.exe: Microsoft C++ exception: std::system_error at memory location 0x03AFDD48.
Unhandled exception at 0x10083C68 (msvcr120d_app.dll) in mySketch_winrt.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.

**Comment by ghost** [comment]
Oh perhaps this explains why?
http://forum.unity3d.com/threads/214291-msvcr120d_app-dll

**Comment by steven-chith** [comment]
Looks like it may be a bug in Poco causing it, but yes, in general you don't want to exit explicitly from Windows Store apps.

**Comment by ghost** [comment]
Sounds good, old habits!  OK feel free to close unless you want to review Poco but I'm fine.  Thank you!
