### ISSUE TITLE
ofShader not working / Platform Guidance required?

### ISSUE THREAD

**Issue by steven-chith** [microsoftarchive/openFrameworks#3]
classic Shader test fails to invert colors. All required files below:
shaderVert.c
# version 120
# extension GL_ARB_texture_rectangle : enable
# extension GL_EXT_gpu_shader4 : enable

void main() {
gl_Position = gl_ModelViewProjectionMatrix \* gl_Vertex;
gl_TexCoord[0] = gl_MultiTexCoord0;
gl_FrontColor = gl_Color;
}
shaderFrag.c
# version 120
# extension GL_ARB_texture_rectangle : enable
# extension GL_EXT_gpu_shader4 : enable

uniform sampler2DRect texture0;

void main(){
//Getting coordinates of the current pixel in texture
vec2 pos = gl_TexCoord[0].xy;

//Getting the pixel color from the texture texture0 in pos
vec4 color = texture2DRect(texture0, pos);

//Changing the color - invert red, green, blue components
color.r = 1.0 - color.r;
color.g = 1.0 - color.g;
color.b = 1.0 - color.b;

//Output the color of shader
gl_FragColor = color;

}
ofApp.cpp

include "ofApp.h"
ofShader shader;
ofFbo fbo;
ofImage image;

void ofApp::setup(){
shader.load("shaderVert.c", "shaderFrag.c");
fbo.allocate(ofGetWidth(), ofGetHeight());
image.loadImage("testPattern.png");
}

void ofApp::draw(){
fbo.begin();
ofBackgroundGradient(ofColor(255), ofColor(128));
ofSetColor(255, 255, 255);
image.draw(351, 221);
fbo.end();
shader.begin();
ofSetColor(255, 255, 255);
fbo.draw(0, 0);
shader.end();
}

The above code only draws the image in the Fbo to the stage, but does not apply any of the shader commands ( in this case, invert the colors ) to the original image.

If shaders ARE implemented in some unique way for Windows Store, please provide a working sample and write out what the key issues are so I can reproduce successfully.

**Comment by steven-chith** [comment]
So, I have SEEN shaders working in OF working previously in the alphaMaskingShaderExample_winrt sample, even though I can't verify the solution anymore since it can't find #include GLES2/gl2.h or #include GLES2/gl2ext.h and errors with: Cannot open include file: 'GLES2/gl2.h': No such file or directory (src\ofApp.cpp) )

So I have to believe this is actually in the Shader versioning instead, so can I please have a blurb of guidance here? What are the "rules" for getting it to work?

Is this needed in every fragment shader?
#ifdef GL_ES
// define default precision for float, vec, mat.
precision highp float;
#endif

Where is #ifdef TARGET_OPENGLES defined?

I thought writing a shader down at 120 would be the lowest common denominator, why are the later version shaders not working?

Can I have some guidance here so I know how to explain it to others?

Thanks,

**Comment by steven-chith** [comment]
Was this project generated with the project generator? It'll set up all the settings correctly so that it can find GLES2/gl2.h. #ifdef TARGET_OPENGLES is found in ofConstants.h line 64.

**Comment by ghost** [comment]
OF Shaders are working, but we need to provide better guidance to the community on the limitations  constraints of working through Angle / OpenGL ES. What versioning should work, how the #ifdef structure should be and where to go to learn more. But I'm ok closing this one since Shaders do work if coded properly.

**Comment by ghost** [comment]
OpenGL ES 2 shaders are currently working. opening separate issue for platform guidance.
