### ISSUE TITLE
Point Size / Point Sprites

### ISSUE THREAD

**Issue by ghost** [microsoftarchive/openFrameworks#30]
Hard to define this as a single bug, the issue is we need to either fix it or provide a work around for Point Sprites.

In the CPU, glPointSize() doesn't work. That could be argued, I guess, makes sense with the angle stuff ( though just fixing it there would be great too).

However, on the GPU, if I add gl_PointSize in a standard vert shader, it doesn't work either.

The main problem we're addressing is the ability to create a point on screen larger than a single pixel, without needing to create all the quads in the CPU.

If this is either using PointSize somewhere and a vertex color, or the ability to create ( via computation shader / DX workaround for lack of Geometry Shader ) a Point Sprite handler in the GPU - that's what the issue is.

**Comment by figment3d** [comment]
GL_POINTS are deprecated in 3.0. It should be easy to replace them by simply drawing a single (front facing) quad in the vertex shader (there would be one per vertex for whatever mesh you chose). Then you could keep track of the point (quad) size the same struct as the light direction.

**Comment by ghost** [comment]
I think the WinRT branch is using ANGLE, and that should be providing access to the OpenGL ES2 specs as would run on iOS.

I don't think you can EmitVertex() on a vert shader, but would need a geometry shader, which is not supported in ES2 so I don't THINK you can us in the WinRT branch of OF, if my Angle wrapping ES2 assumption is correct.

However, the need to either paint Points of variable size through the GPU or leverage some DX / Compute Shader work around ( assuming the feature level of the Windows device is at least 10.1+ I believe ) to do exactly what you're saying ( create a QUAD in the GPU that we can then texture bind to ) is what needs to get solved / work around provided.

Still trying a couple other things, but there may be a "switch" somewhere in the code that is simply disabling a feature ifdef winrt, maybe?

**Comment by steven-chith** [comment]
Point sprites in ANGLE use DX11 geometry shaders, which don't work on DX9 hardware. Even stranger is that point sprites worked in DX9, but was removed in DX11. This has been quite an issue for the winrt implementation for a long time now. I can try to do an implementation of point sprites with quads in ANGLE for feature level 9. There doesn't seem to be any other way to do it.

**Comment by stammen** [comment]
Angle is supposed to use the higher versions of DirectX if it is running on a device that can handle it and is build with VS2013. There must be a bug preventing it from using the geometry shaders on these devices. It already uses level 4 shaders if on DirectX 10 or higher.

Can you look at what is happening in the code and give us an estimate on what it will take to fix.

**Comment by steven-chith** [comment]
Sorry, let me clarify, when I mentioned DX9 hardware before I meant DX11 feature level 9. You need at least feature level 10 to use geometry shaders.

**Comment by stammen** [comment]
Geometry shaders should be enabled for winrt on devices with DX11 feature level 10 and higher when compiled with VS2013.  Please investigate.

**Comment by figment3d** [comment]
I can see where there would be circular logic drawing a quad within a vertex shader, requiring geometry shaders.

But perhaps a pixel shader method would work instead. Since all point sprites are drawn the same size (the ones in the distance are not smaller normally), maybe if the whole screen were overlayed with a single texture map, the pixels in that image could be colored in at the corresponding (perspective corrected) location of the vertices. Then, the resolution of that image could be changed to increase point size. I would imagine each sprite would need to be a 4x4 kernel (or so) to support overlapping points (similar to blending algorithms such as Gaussian blur).

Date: Fri, 11 Apr 2014 10:31:31 -0700

**Comment by figment3d** [comment]
This article on gamedev discusses an HLSL Point Sprite Pixel Shader that looks fairly simple.

http://www.gamedev.net/topic/413044-rendering-point-sprites-with-a-pixel-shader/

**Comment by steven-chith** [comment]
Got point sprites working now. The way ANGLE does them under the hood is purely through shaders. You can't call glPointSize or glEnable(GL_POINT_SPRITES) since it's not supported by OpenGLES 2.0. OF does this under the hood, but it seems they made it against the OpenGLES 1.1 standard, so I had to disable those calls for winrt. Here are the most basic of shaders you need to make them work.

Vertex shader:

``` c++
precision highp float; //or whatever other precision you want

attribute vec4 position;

void main(void)
{
    gl_Position = position;
    gl_PointSize = 10.0; //modify point size here
}
```

Fragment shader

``` c++
precision highp float; //or whatever other precision you want

uniform sampler2D uTexture;

void main(void)
{
    //gl_PointCoord is the built-in for point sprite texture coordinates
    gl_FragColor = texture2D(uTexture, gl_PointCoord);
}
```

**Comment by ghost** [comment]
OK –

This one took me FOREVER to figure out.

This solution only works from the NON-XAML solution for the project.

So for example, “pointTest_winrt.sln” would work fine, but if you try and open “pointTest_winrt_xaml.sln”, it stops working.

This drove me crazy realizing that was the problem. It’s the same for every project.

Now, in general, if you try and open an “xxx_wnrt.sln” and then open the “xxx_winrt_xaml.sln”, you need to go to Package.Appxmanifest and change the unique number there or you get errors. You also need to make sure that the data folder, pngs and shaders are added to BOTH solutions so there is parity…

But even after doing all that, the exact same code only renders when you DON’T have the XAML layer over it.

NOTE: I really need to XAML layer for this, because I’m data binding run time variables to XAML slider controls. Its kind of a big selling point for us adding XAML.

Any idea why XAML will suddenly break the Point Sprites?

**Comment by steven-chith** [comment]
Had to get the XAML case to build the latest OpenGL context. Works now.
