### ISSUE TITLE
Project generator doesn't add assets within folders in data directory

### ISSUE THREAD

**Issue by steven-chith** [microsoftarchive/openFrameworks#34]
Need to recursively add the files within the directories of the data folder to the solution.

**Comment by stammen** [comment]
There is a way to do this automatically by adding code to the winrt app's vcxproj file. Look at how we did it in cocos2d-x

https://github.com/MSOpenTech/cocos2d-x/blob/v2/samples/Cpp/TestCpp/proj.winrt/TestCpp.vcxproj

Search for the word RecursiveDir. Add the code to the OF app .vcxproj file

You will need to modify the path specified by <_CustomResource Include="..\Resources*_\_"> to point to the data or bin dir.

This method was suggested by the Visual Studio team.

 <ItemGroup>
    <_CustomResource Include="..\Resources*_\_">
      <Link>Assets\Resources\%(RecursiveDir)%(FileName)%(Extension)</Link>
      <DeploymentContent>true</DeploymentContent>
    </_CustomResource>
  </ItemGroup>
