### ISSUE TITLE
need to handle std::cout on winrt

### ISSUE THREAD

**Issue by stammen** [microsoftarchive/openFrameworks#36]
Some of the examples use std::cout to display text which shows nothing on winrt. For example the videograbber example uses cout to list the video devices.

Based on your experience with the OF code, what do you suggest we do.

**Comment by steven-chith** [comment]
Normally, OF apps bring up the console so cout just outputs to that. I think the better way to go about it is not to use cout, but to use the ofLog functions. They'll either output to stdout or the Visual Studio output for winrt.
