### ISSUE TITLE
WinRT project generator modifies main.cpp in examples dir

### ISSUE THREAD

**Issue by stammen** [microsoftarchive/openFrameworks#38]
WinRT project generator modifies main.cpp in examples dir. Since main.cpp is a file that already commited to the OF repo, git status will report that the file has been modified. Even with .gitignore now ignoring the examples folder, git status will still report the file as modified. This will be confusing to the user and will also create problems with rebasing since the file will need to be committed.

Possible solutions:

1.WinRT Project Generator creates a new main file called winrt_main.cpp.
1. Drop the C++ only version of OF since xaml version does not need main.cpp.
2. Other suggestions?

**Comment by steven-chith** [comment]
No saving modifications.
