### ISSUE TITLE
mesh.addTexCoord() works differently in OF / not implemented correctly

### ISSUE THREAD

**Issue by steven-chith** [microsoftarchive/openFrameworks#4]
I almost wrote that the image.bind() wasn't working, but it turns out that the texture mapping is "wrong". I put "wrong" in quotes, because we actually wrote it the way texture mapping usually works ( mapping uv from 0.0 to 1.0 of the image size ). HOWEVER - OF lets users texture map based on ACTUAL PIXEL DIMENSIONS.

so if I'm binding a 500x500 pixel image, I'm SUPPOSED TO DO this in OF:
mesh.addTexCoord(ofPoint(0, 0));
mesh.addTexCoord(ofPoint(0, 500));
mesh.addTexCoord(ofPoint(500, 500));

AND NOT THIS, WHICH IS WHAT OUR CURRENT CODE IS EXPECTING (BUT NOT HOW OF DOES IT):
mesh.addTexCoord(ofPoint(0.0, 0.0));
mesh.addTexCoord(ofPoint(0.0, 1.0));
mesh.addTexCoord(ofPoint(1.0, 1.0));

**Comment by steven-chith** [comment]
Are you absolutely sure? Is there a sample program you're referring to you can show me? Such a design decision would be very bad for 3D models.

**Comment by steven-chith** [comment]
Dude, I know. It seems crazy to me, but that is the way they do it in OF. 

Reference: http://www.openframeworks.cc/documentation/3d/ofMesh.html#show_addTexCoord

You'll see that they argue it this way:

void ofMesh::addTexCoord(const ofVec2f &t)

Add a Vec2f representing the texture coordinate. Because OF uses ARB textures these are in pixels rather than 0-1 normalized coordinates.

Now, if we only have you for a bit more, I wouldn't list this as the top priority but would prioritize other fixes ( since you can still at least USE it the more traditional, normalized way for now and it works fine ). But we need to raise this up to the community and hopefully this is a great example of something the community may want to assist with?

**Comment by steven-chith** [comment]
Okay, so this is quite interesting. There's a bit of inconsistency in the code and documentation when dealing with texture coordinates. For example, when drawing a texture with ofImage, under the hood if it's not targeting OpenGL ES it'll use non-normalized texture coordinates provided the texture is set to do that. Otherwise, when targeting OpenGL ES it will use normalized coordinates. ofMesh doesn't do any sort of check and only assumes non-normalized coordinates. Since angle is based on OpenGL ES 2.0 we "target" it for the winrt implementation of OF. The reason they do this targeting is because OpenGL ES doesn't support non-normalized coordinates. That means any apps that use ofMesh on Android or iOS need to take this into consideration.

**Comment by ghost** [comment]
please regard this as P2

**Comment by steven-chith** [comment]
After looking through the OF code, I've found no evidence to suggest that OpenGL ES apps are to use absolute pixel coordinates. Even the vboExample app normalizes its own texture coordinates if on OpenGL ES. First off, they call this function called ofEnableNormalizedTexCoords() which tells the renderer to set itself up for normalized texture coordinates and does a few other things under the hood, so that's how to handle the special case of OpenGL ES apps.
