### ISSUE TITLE
ofVideoPlayer loads video, but when data is referenced, stops playing

### ISSUE THREAD

**Issue by ghost** [microsoftarchive/openFrameworks#41]
Doing a simple test like: 

ofVideoPlayer video;

setup() { ...   video.load("test.mov"); ... }
update() { ... video.update(); ... }
draw() { ... video.draw(0,0); }

Works fine. But when I start DOING something with it, the dependability of having a frame update virtually stops. So for example, something more advanced like this classic demo:
# include "ofApp.h"

ofVideoPlayer video;
ofImage image;
int table[16];

void ofApp::setup(){
    video.loadMovie("handsTrees.mov");
    video.play();

```
for (int i = 0; i<16; i++) {
    table[i] = ofRandom(0, 255);
}
```

}

void ofApp::update(){
    video.update();
    if (video.isFrameNew()) {
        ofPixels pixels = video.getPixelsRef();
        for (int y = 0; y<pixels.getHeight(); y++) {
            for (int x = 0; x<pixels.getWidth(); x++) {
                ofColor col = pixels.getColor(x, y);
                col.r = table[col.r / 16];
                col.g = table[col.g / 16];
                col.b = table[col.b / 16];

```
            pixels.setColor(x, y, col);
        }
    }
    image.setFromPixels(pixels);
    pixels.clear();
}
```

}

void ofApp::draw(){
    image.draw(0, 0);
    video.draw(600, 0);
}

It stops responding, in both debug and release.

The video loads and you see a first frame, but it the frames stop updating.

This is regardless of how long you wait after it stops. Once it stops, it stops.

Occassionally, you may notice it process the first 2 or 3 frames before stopping, but it then it stops.

Can someone reproduce code and validate? This is on my Mac Book Pro running Windows 8.1 update 1 and is what I use for all the testing.

**Comment by ghost** [comment]
Additional input:

I added a timestamp() output in my draw loop to make sure that the draw() commands were still getting called and the system wasn't just frozen:

```
ofDrawBitmapString("TIME:", ofPoint(10, 600));
ofDrawBitmapString(ofGetTimestampString(), ofPoint(70, 600));
```

And that works fine. You add that to the above code and you'll see that you still get the draw command firing regularly. Though the Video has stopped advancing in frame when something goes wrong (but doesn't crash the app) with the:

ofPixels pixels = video.getPixelsRef();

Here are the repeating error warnings in the OUTPUT window after I stop running the app.

[ error ] ofPixels: allocate(): unknown image type, not allocating
[ error ] ofPixels: setFromPixels(): image type 3 not supported, not copying
[warning] ofGLProgrammableRenderer: draw(): texture is not allocated

The movie used is an 18MB MOV file, btw. If that helps track this down.

**Comment by steven-chith** [comment]
Doesn't seem to be happening anymore, although I tested it with a 3MB movie. Not sure if size would have anything to do with it, but give it a try and see what happens. You'll see that "texture not allocated" message until the movie starts playing since it's all asynchronous under the hood.
