### ISSUE TITLE
ofLight doesn't work

### ISSUE THREAD

**Issue by steven-chith** [microsoftarchive/openFrameworks#5]
Hmmm.. this one is kind of important in terms of learning, because students usually are first introduced to normals and vertices by using these "easy to use" defaults. So while it is beginner, OF is optimized for beginner. Here is how you use it:

ofMesh mesh;
ofLight light;

void ofApp::setup() {

}

void ofApp::setup(){
    //Pyramid's base vertices
    ofPoint v0 = ofPoint(-200, -100, 0);
    ofPoint v1 = ofPoint(200, -100, 0);
    ofPoint v2 = ofPoint(0, 200, 0);
    //Pyramid's top vertex
    ofPoint v3 = ofPoint(0, 0, 100);
    //Add triangles by its vertices
    mesh.addVertex(v3); mesh.addVertex(v2); mesh.addVertex(v0);
    mesh.addVertex(v3); mesh.addVertex(v1); mesh.addVertex(v2);
    mesh.addVertex(v3); mesh.addVertex(v0); mesh.addVertex(v1);
    mesh.setupIndicesAuto();    //Set up indices
    setNormals(mesh);  // custom function that sets the normals, ping me if you need it.

```
//Enabling light source
    // ****************************
    // THIS IS THE PART THAT DOESN'T WORK. THERE IS NOT CHANGE IN LIGHTING
    // IN THE DRAW FUNCTION. THE MESH COMES OUT SOLID GREEN THROUGHOUT
light.enable();
```

}

//--------------------------------------------------------------
void ofApp::draw(){
    ofEnableDepthTest();
    ofBackgroundGradient(ofColor(255), ofColor(128));
    ofPushMatrix();
    ofTranslate(ofGetWidth() / 2, ofGetHeight() / 2, 0);
    float time = ofGetElapsedTimef();
    float angle = time \* 30;
    ofRotate(angle, 0, 1, 1);
    ofSetColor(0, 128, 0);
    mesh.draw();
    ofPopMatrix();
}

( Below is the setNormals universal function as reference - though ofLight doesn't seem to effect anything and it should, based on the normals assigned correctly as follows: )

// UNIVERSAL FUNCTION WHICH SETS NORMALS FOR THE TRIANGLE MESH
void setNormals(ofMesh &mesh)
{
    int nV = mesh.getNumVertices();
    int nT = mesh.getNumIndices() / 3;
    vector<ofPoint> norm(nV);

```
for (int t = 0; t < nT; t++)
{
    int i1 = mesh.getIndex(3 * t);
    int i2 = mesh.getIndex(3 * t + 1);
    int i3 = mesh.getIndex(3 * t + 2);
    const ofPoint &v1 = mesh.getVertex(i1);
    const ofPoint &v2 = mesh.getVertex(i2);
    const ofPoint &v3 = mesh.getVertex(i3);

    // compute the triangle's normal
    ofPoint dir = ((v2 - v1).crossed(v3 - v1)).normalized();

    // accumulate it to norm array for i1, i2, i3
    norm[i1] += dir;
    norm[i2] += dir;
    norm[i3] += dir;
}

for (int i = 0; i < nV; i++) {
    norm[i].normalize();
}
mesh.clearNormals();
mesh.addNormals(norm);
```

}

**Comment by steven-chith** [comment]
The ofLight is meant not to work when using a programmable renderer. It uses deprecated fixed-function lighting in old OpenGL. Even when using vanilla oF if you enable the programmable renderer it won't light properly. For it to work they, as in the oF authors, or us, need to write shaders for lighting and modify the code path for having lights enabled.

**Comment by ghost** [comment]
this is an OpenGL ES issue (fixed rendering pipeline). We can't make it work on the current API
