### ISSUE TITLE
Project template needs to be restore to empty project

### ISSUE THREAD

**Issue by stammen** [microsoftarchive/openFrameworks#50]
Universal branch is currently using the 3dPrimitives example for the project generator template. We need to update the template to be an empty OF project.

**Comment by uvollono** [comment]
Start from a basic 3d primitives examples was a good idea. You find the issue cause the videograbber breaking?

I didn't use any video camera

**Comment by stammen** [comment]
I looks like there is a bug that the video grabber will crash if there is no video camera. We will investigate.

For now, feel free to comment out the camera code in the sample.

**Comment by uvollono** [comment]
Amazing!
I comment all the vidGrabber code lines from ofApp .h and .cpp so now work fine!

**Comment by uvollono** [comment]
Stammen I cannot build also advanced3dexample from example folder (both winphone and win8.1)

I create a sketch project, deleted main and ofApp files, cleaned project, added all the advanced3dexamples files and rebuild, but I receive:

Error   30  error LNK1120: 1 unresolved externals   C:\openFrameworks\openFrameworks-universal\apps\myApps\advanced3dexample\Debug\advanced3dexample.Windows\advanced3dexample.Windows.exe  advanced3dexample.Windows
Error   29  error LNK2001: unresolved external symbol "void __cdecl ofmain(void)" (?ofmain@@YAXXZ)  c:\openFrameworks\openFrameworks-universal\apps\myApps\advanced3dexample\advanced3dexample\advanced3dexample.Windows\Renderer.obj   advanced3dexample.Windows
Error   25  error LNK2005: "?main@@YAHP$01$AAV?$Array@P$AAVString@Platform@@$00@Platform@@@Z" (?main@@YAHP$01$AAV?$Array@P$AAVString@Platform@@$00@Platform@@@Z) already defined in main.obj    c:\openFrameworks\openFrameworks-universal\apps\myApps\advanced3dexample\advanced3dexample\advanced3dexample.Windows\XamlTypeInfo.g.obj advanced3dexample.Windows

Any suggest?

**Comment by stammen** [comment]
change the function main() to void ofmain()

**Comment by uvollono** [comment]
Thanks for the support.

I replaced the main.cpp (with 3dprimitive main.cpp) before your comment but VS didn't refresh the main.cpp !!!
A clean up solution fixed my issue.

Thanks
