### ISSUE TITLE
Screen scaling is way off in Universal Apps

### ISSUE THREAD

**Issue by ghost** [microsoftarchive/openFrameworks#53]
Start a Universal App project, go to the Windows Store project and add this to your draw() function:

ofDrawBitmapString("Dimensions: "
             + ofToString(ofGetWidth())  + ", " 
             + ofToString(ofGetHeight()), 
             ofPoint(10, 450));

And on my 2560 x 1600 machine, I'll still get a result of: 1422, 888

I'd have to scale everything down by 0.740625 to get back to even, but that's not a viable option ( least of all cause all my shaders would need reworking too ).

We ran into this issue an the winrt branch and resolved it there, but looks like it got lost along the way migrating OF to a Universal App. Can we recheck the screen scale / DPI issues again and make sure the work for Store and Phone again?

**Comment by ghost** [comment]
I reviewed this last night because I was having the same issue with the winrt branch.  Fix from the winrt-multitouch branch has been included in universal but it's way different.  I'm not familiar with this branch to resolve atm.

I was testing on a MacBook Pro 2014 w/ Retina.

**Comment by steven-chith** [comment]
I'll look into it after finishing up some updates to ANGLE.

**Comment by steven-chith** [comment]
The scaling and input are fixed now.
