### ISSUE TITLE
Can't compile out of box with VS 2013

### ISSUE THREAD

**Issue by ghost** [microsoftarchive/openFrameworks#54]
I gotta admit, I'm a little shocked. I grabbed this repo because I can't get the master/original branch to compile properly with VS2013. I thought this one would for sure work, but nope. Out of the box, have to change toolset, as no VS2013 project file, has to be upgraded. That's fine. Next, ofVbo.cpp line 330:

supportVAOs = ofGetGLProgrammableRenderer();

Compilation error, casting ofPtr<TYPE> to bool. Perhaps it's relying on boolean operator in the type ofPtr to see if the internal pointer is actually referencing an object or is null? Haven't looked but this is the only logical explanation without this entire line being a total blunder. If that's the case, needs a static cast to bool to be corrected.

**Comment by ghost** [comment]
Also, appears I have to get poco sources and recompile with vs2013 as I'm getting:

Error   176 error LNK2038: mismatch detected for '_MSC_VER': value '1700' doesn't match value '1800' in XXX
a bunch of times. So yeah, VS2013 totally not supported out of box.

UPDATE
Also have to recompile openCV.

**Comment by ghost** [comment]
Hey TechnikEmpire, 

If you're just looking to use OpenFrameworks on VS2013, which isn't officially supported in OF proper, must people just use LiquidZym's branch off of GitHub.

I have a step by step tutorial online here (for now): http://rbarraza.azurewebsites.net/2014/11/15/setting-up-openframeworks-x64-kinect-v2-for-visual-studio-2013/

If you specifially are looking at MSOT's branch to experiment with OF for Windows Store ( the only branch that does that for you, but it's still being developed ), then make sure you have switched to the WinRT branch or the most recent "Universal" branch.

That has been building fine for months.

HOWEVER - as of this very moment, there is an ambiguation error around some newer compilter / POCO stuff at TlsAlloc(). I'm sure the MSOT team will get this fixed asap.

Otherwise, the Universal Branch has been very good and I've been using it for OF for Windows Store work for a long time now.

For OF work in Visual Studio 2013, though, I and most people are just using the LiquidZym branch I reference above.

For all other work, it is easiest to just use the official OF release and VS2012. They're looking into adding VS2013 or VS2014 support right now, but it is still not "officially" supported, as all the poco libraries and everything else have to be rebuilt too. ( We're all in the same boat! ;)  

Hope that helps,

**Comment by stammen** [comment]
We are looking at the problem on Monday.
