### ISSUE TITLE
x64 Windows Link Error with latest build

### ISSUE THREAD

**Issue by mscherotter** [microsoftarchive/openFrameworks#59]
1. Universal Branch from 11/17/2014
2. Building with Visual Studio 2013 Update 4
3. Created WinRT Universal app with project generator and default options
4. All builds except for X64 build and run:
5. x64 build fails with this error:
   1>LINK : fatal error LNK1181: cannot open input file 'FreeImage.lib'

**Comment by stammen** [comment]
There is no x64 support at this time.
