### ISSUE TITLE
ofVideoGrabber not functioning properly

### ISSUE THREAD

**Issue by steven-chith** [microsoftarchive/openFrameworks#6]
DOCUMENTING. It instantiates fine, asks for permission to use WebCam, but goes wonky ( green, bad spliced, etc.) immediately. Low framerate in both debug and release.

CODE TO REPRODUCE:

ofVideoGrabber grabber; //Video grabber

void ofApp::setup(){
grabber.initGrabber(1024, 768);
}

void ofApp::update(){
grabber.update();
}

void ofApp::draw(){
ofBackground(128,128,128); //Set the background color
ofSetColor(255, 255, 255);
grabber.draw(0, 0);
}

**Comment by steven-chith** [comment]
Will fix when new camera code is ready.

**Comment by ghost** [comment]
P1 - this blocks video scenarios

**Comment by stammen** [comment]
fixed in video3 branch. Will merge into multitouch branch after final testing.
