### ISSUE TITLE
Unsupported windows version when building

### ISSUE THREAD

**Issue by xfischer** [microsoftarchive/openFrameworks#63]
I have this error message while building from VS2013 Community on Windows 8.1
Can you help me with this ?

**Comment by stammen** [comment]
@xfischer What is the error message?

**Comment by xfischer** [comment]
Sorry for the late answer. The message is "Unsupported windows version"... I have switched to the https://github.com/liquidzym/openframeworks_X64/tree/VS2013_X64 version from LiquidZym and the error was gone.

**Comment by quinkennedy** [comment]
so the problem is that ofConstants.h defines _WIN32_WINNT as 0x500, and Poco/UnWindows.h errors during pre-processing if _WIN32_WINNT < 0x0501

I'm trying to compile the devApps/projectGenerator at the moment
