### ISSUE TITLE
ofSoundStream can't bind to Project

### ISSUE THREAD

**Issue by steven-chith** [microsoftarchive/openFrameworks#7]
This one is tricky to explain - I've been testing out soundPlayer this morning ( totally awesome, btw! ), but now working on generating soundStreams ( to make your own synth, etc. ) 

If you create an ofSoundStream, you need to define an audioOut() function which OpenFrameworks calls independently from the update/draw loop once you setup() the soundStream. As you can see below ( and this sample comes from a working demo in OF desktop ), I setup the ofSoundStream and handle the buffers correctly, but OF isn't pulling from audioOut() I believe.

I think the most likely cause is when I setup ofSoundStream() in this line during setup():
        // ****\* HERE IS THE PROBLEM I THINK ****************\*  
    soundStream.setup(this, 2, 0, sampleRate, bufSize, 4);

You'll notice I have to pass in "this", and that may be doing it? I also found a common issue when working with ofSoundStream, which says:

"In some compilers, you need to perform the REBUILD command for your project in order for the audioOut() function to be linked to the project correctly. If the linking is not correct, you will just see a straight line [NOTE: Which is what I see when I run this on RT] on the screen and hear nothing."

However, I did a REBUILD hoping that would do it, and it rebuilt OFLIB and the Project together, but still, nothing came out. I was just generating a flat line.

Here is the code to reproduce on your end.
# in my ofApp.h I have added:

```
    ofSoundStream soundStream;  //Object for sound output setup
    //Function for generating audio
    void audioOut(float * input, int bufferSize, int nChannels);
    //User-changing parameters
    float userFreq;             //Frequency
    float userPwm;              //PWM-value
    //Parameters, used during synthesis
    float freq;                 //Current frequency
    float pwm;                  //Current PWM-value
    float phase;                //Phase of the wave
    //Buffer for rendering last generated audio buffer
    vector<float> buf;
```
# and in ofApp.cpp, I have added:

int bufSize = 512;      //Sound card buffer size
int sampleRate = 44100; //Sound sample rate
float volume = 0.1;     //Output volume
//--------------------------------------------------------------
void ofApp::setup(){
    userFreq = 100.0;       //Some initial frequency
    userPwm = 0.5;      //Some initial PWM-value
    freq = userFreq;
    pwm = userPwm;
    phase = 0;
    buf.resize(bufSize);
    //Start the sound output
        // ****\* HERE IS THE PROBLEM I THINK **************
        // CALLING SETUP ON THE SOUND STREAM SHOULD INVOKE
        // OF TO AUTOMATICALLY START POLLING THE AUDIOOUT() 
        // FUNCTION BEFORE SENDING TO SOUND CARD....
    soundStream.setup(this, 2, 0, sampleRate, bufSize, 4);
}

Here are the rest of the supporting functions in .cpp if you want to duplicate:
void ofApp::draw(){
    ofBackground(255, 255, 255);    //Set the background color  
    //Draw the buffer values
    ofSetColor(0, 0, 0);
    for (int i = 0; i<bufSize - 1; i++) {
        ofLine(i, 100 - buf[i] \* 50, (i + 1), 100 - buf[i + 1] \* 50);
    }
}

//--------------------------------------------------------------
void ofApp::audioOut(float \* output, int bufferSize, int nChannels){
    //Fill output buffer,
    //and also move freq to userFreq and pwm to userPWM slowly
    for (int i = 0; i<bufferSize; i++) {
        //freq smoothly reaches userFreq
        freq += (userFreq - freq) \* 0.001;
        //pwm smoothly reaches userPwm
        pwm += (userPwm - pwm) \* 0.001;

```
    //Change phase, and push it into [0, 1] range
    phase += freq / sampleRate;
    phase = fmodf(phase, 1.0);

    //Calculate the output audio sample value
    //Instead of 1 and 0 we use 1 and -1 output values
    //for the sound wave to be symmetrical along y-axe
    float v = (phase < pwm) ? 1.0 : -1.0;

    //Set the computed value to the left and the right
    //channels of output buffer,
    //also using global volume value defined above
    output[i * 2] = output[i * 2 + 1] = v * volume;

    //Set the value to buffer buf, used for rendering
    //on the screen
    //Note: bufferSize can occasionally differ from bufSize
    if (i < bufSize) {
        buf[i] = v;
    }
}
```

}
void ofApp::mouseMoved(int x, int y ){
    userFreq = ofMap(x, 0, ofGetWidth(), 1, 2000);
    userPwm = ofMap(y, 0, ofGetHeight(), 0, 1);
}

**Comment by steven-chith** [comment]
The audio stream is still a work in progress. It builds and runs, but it doesn't quite get the sound stream yet. There's an underlying race condition preventing the initialization of the audio devices that I need to hammer away.

**Comment by steven-chith** [comment]
I got the audio stream working. Give it a try on your end.

**Comment by steven-chith** [comment]
Hey, I'm getting an access violation. Can you maybe add what your test was? Here is my test that is crashing. Would love to see if it works on your end / you can see why it isn't working yet? Copy / Paste below should be all you need to test on your end.

---

## ofApp.h

#pragma once

#include "ofMain.h"

class ofApp : public ofBaseApp{

```
public:
    void setup();
    void update();
    void draw();

    ofSoundStream soundStream;  //Object for sound output setup

    //Function for generating audio
    void audioOut(float * input, int bufferSize, int nChannels);

    //User-changing parameters
    float userFreq;             //Frequency
    float userPwm;              //PWM-value

    //Parameters, used during synthesis
    float freq;                 //Current frequency
    float pwm;                  //Current PWM-value
    float phase;                //Phase of the wave

    //Buffer for rendering last generated audio buffer
    vector<float> buf;

    void keyPressed(int key);
    void keyReleased(int key);
    void mouseMoved(int x, int y );
    void mouseDragged(int x, int y, int button);
    void mousePressed(int x, int y, int button);
    void mouseReleased(int x, int y, int button);
    void windowResized(int w, int h);
    void dragEvent(ofDragInfo dragInfo);
    void gotMessage(ofMessage msg);
```

};

---

## ofApp.cpp

#include "ofApp.h"

int bufSize = 512;      //Sound card buffer size
int sampleRate = 44100; //Sound sample rate
float volume = 0.1;     //Output volume

//--------------------------------------------------------------
void ofApp::setup(){

```
userFreq = 100.0;       //Some initial frequency
userPwm = 0.5;          //Some initial PWM-value

freq = userFreq;
pwm = userPwm;
phase = 0;
buf.resize(bufSize);

//Start the sound output    
soundStream.setup(this, 2, 0, sampleRate, bufSize, 4);
soundStream.start();
```

}
void ofApp::update(){
}
void ofApp::draw(){
    ofBackground(255, 255, 255);    //Set the background color  
    //Draw the buffer values
    ofSetColor(0, 0, 0);
    for (int i = 0; i<bufSize - 1; i++) {
        ofLine(i, 100 - buf[i] \* 50, (i + 1), 100 - buf[i + 1] \* 50);
    }
}
void ofApp::audioOut(float \* output, int bufferSize, int nChannels){
    //Fill output buffer,
    //and also move freq to userFreq and pwm to userPWM slowly
    for (int i = 0; i<bufferSize; i++) {
        //freq smoothly reaches userFreq
        freq += (userFreq - freq) \* 0.001;
        //pwm smoothly reaches userPwm
        pwm += (userPwm - pwm) \* 0.001;

```
    //Change phase, and push it into [0, 1] range
    phase += freq / sampleRate;
    phase = fmodf(phase, 1.0);

    //Calculate the output audio sample value
    //Instead of 1 and 0 we use 1 and -1 output values
    //for the sound wave to be symmetrical along y-axe
    float v = (phase < pwm) ? 1.0 : -1.0;

    //Set the computed value to the left and the right
    //channels of output buffer,
    //also using global volume value defined above
    output[i * 2] = output[i * 2 + 1] = v * volume;

    //Set the value to buffer buf, used for rendering
    //on the screen
    //Note: bufferSize can occasionally differ from bufSize
    if (i < bufSize) {
        buf[i] = v;
    }
}
```

}
void ofApp::keyPressed(int key){
}
void ofApp::keyReleased(int key){
}
void ofApp::mouseMoved(int x, int y ){
    userFreq = ofMap(x, 0, ofGetWidth(), 1, 2000);
    userPwm = ofMap(y, 0, ofGetHeight(), 0, 1);
}
void ofApp::mouseDragged(int x, int y, int button){
}
void ofApp::mousePressed(int x, int y, int button){
}
void ofApp::mouseReleased(int x, int y, int button){
}
void ofApp::windowResized(int w, int h){
}
void ofApp::gotMessage(ofMessage msg){
}
void ofApp::dragEvent(ofDragInfo dragInfo){ 
}

**Comment by steven-chith** [comment]
The thing I was testing was examples/sound/audioInputExample. It's an interesting app.

I fixed another race condition in the audio, so try pulling again and see if that does anything. Your app doesn't crash on me at all, but maybe this will do the trick.

**Comment by ghost** [comment]
Rick to repro this. It should be fixed by now

**Comment by stammen** [comment]
Rick, any comments on this issue?

**Comment by stammen** [comment]
Closed.
