### ISSUE TITLE
ofVideoPlayer() not working

### ISSUE THREAD

**Issue by steven-chith** [microsoftarchive/openFrameworks#8]
Documenting features not implemented in RT:

Test:

ofVideoPlayer video;
void ofApp::setup(){
    video.loadMovie("handsTrees.mov");  //Load the video file
    video.play();           //Start the video to play  
}

void ofApp::update(){
    video.update();         //Decode the new frame if needed
}

void ofApp::draw(){
    ofBackground(255, 255, 255);    //Set white background
    ofSetColor(255, 255, 255);
    video.draw(0, 0);           //Draw the current video frame
}

**Comment by ghost** [comment]
P1- research if Angle can be modified to accept DX textures.

**Comment by steven-chith** [comment]
So ANGLE can be modified to accept DX textures rather easily, but there's another issue with the video player. Using the media foundation API, it can write to a DX texture, but it needs to be copied to another DX texture to be able to be written to. For some reason, the media foundation API can only write to a DX texture designed for reads and writes via the graphics driver only, so we need to create a separate texture designed for CPU reads and blit the first texture to this one. OF needs the pixels stored client side to draw and modify them, so no need to try to pass the DX texture directly to ANGLE.

Either way, the video playback works and performance is reasonable. If performance becomes an issue we can look into this again.
