### ISSUE TITLE
ofImage.saveImage() not working

### ISSUE THREAD

**Issue by steven-chith** [microsoftarchive/openFrameworks#9]
ofImage is pretty good. You can load easily, and manipulate pixel data very nicely ( as perfomant as desktop version too).

However, as with saving files from the buffer stream, calling ofImage.saveImage("filename.png") doesn't return an error, but doesn't actually save it anywhere.

Ideally, it may be that we need to set the flag to be able to save to documents, and calling saveImage() from a Store app would create a unique folder in the Pictures directory with the name of the app, and then start saving the image there - as a suggestion.

But wherever it get's saved, we're going to need to ability to save both text and image files, not just load them.

**Comment by steven-chith** [comment]
I modified the file pathing for image saving just like the ofBuffer thing. If you wanted to find the images they're usually in C:\Users<your user name>\AppData\Local\Packages<a combination of the GUID and something else>\LocalState. It saves images out here now.

**Comment by steven-chith** [comment]
Can't we save to the Pictures folder so the user can find their pictures?

**Comment by steven-chith** [comment]
Oh yeah, that would be better. I'll get to it soon.

**Comment by steven-chith** [comment]
ofImage saves to the pictures directory now.

**Comment by ghost** [comment]
please modify behavior to save in a openFrameworks/[applicationname] subfolder within the pictures directory.

be consistent with iOS behavior if possible

**Comment by steven-chith** [comment]
I got the images saving to the Pictures/[applicationname] directory. I omitted openFrameworks since the average user may not know what openFrameworks is, but will definitely know the name of their app that saved the picture.
